### ISSUE TITLE
Feature plugin extension roadmap

### ISSUE THREAD

**Issue by dmolineus** [phpcq/phpcq#48]
This issues is a collection of multiple steps which are required for the planned plugin extension.

**repository (builder)**

- [X] Rework repositories to distinguish between plugins and tools phpcq/repository-builder#6
  - Implemented via phpcq/repository-builder#8
- [X] Add support for extended requirements phpcq/repository-builder#7
  - Implemented via phpcq/repository-builder#8

**plugin-api**

- [x] Introduce a new `ExecPlugininterface` phpcq/plugin-api/issues/9
- [x] Allow a plugin to define composer requirements

**phpcq**

- [x] Change configuration format. Should be possible as a first standalone change
- [x] Support new repository format
- [x] Allow tool requirements for plugins
- [x] Allow composer requirements for plugins #64 
- [x] Decide and maybe support plugin requirements for plugins
- [x] Rework updater so that each plugin has its own install directory with local dependencies

**plugins**
- [x] Adopt api changes

**Comment by dmolineus** [comment]
Closing issue as all steps are implemented.
